### ISSUE TITLE
inception: "has not understood" and "✔ has 22"

### ISSUE THREAD

**Issue by HenrikBengtsson** [kdabir/has#22]
It feels like `has` should handle itself, eh ;)
```sh
$ has has
✘ has not understood
```
And even it was hard coded to do so, it parses its own version incorrectly:
```sh
$ HAS_ALLOW_UNSAFE=y has has
✔ has 22
```
This is using:
```sh
$ has
has v1.1.0
USAGE:    has <command-names>..
EXAMPLE:  has git curl node
```

First time here. Thanks for an interesting tool. In the best of the best world, all software tools should have versions and there should be a standard way of querying it.

**Comment by kdabir** [comment]
hey @HenrikBengtsson, thanks for reporting the very interesting issue :)
Fixed in 3136085

Still not adding support for `-v` flag as of yet to `has` to just keep it simple
