### ISSUE TITLE
support quiet mode

### ISSUE THREAD

**Issue by kdabir** [kdabir/has#39]
support `-q` of something similar to disable output for command line. This can be useful in scripts using `has` only for the exit status code.

**Comment by JCBrown602** [comment]
Could this be achieved by routing stdout to /dev/null? If I'm on the right track, I will try to solve this as my first real issue. I also read a bit about getopt/getopts - looks like that may be how it will work.

**Comment by kdabir** [comment]
@JCBrown602 thanks for volunteering.

> Could this be achieved by routing stdout to /dev/null?

yes either that or by nesting the `echo`s under `if` checks. The idea is to solve it the simplest way and refactor as needed. Just make sure to add test covering the scenario you add so that we can refactor with confidence in future.
